### ISSUE TITLE
Dev Server sometimes crashes

### ISSUE THREAD

**Issue by kimhung222** [Dwlad90/stylex-swc-plugin#81]
When I start dev server. Sometimes I encouter this issue, I must start the server again.

![image](https://github.com/user-attachments/assets/ca025530-3c90-42ac-9084-458632386bf9)

**Comment by Dwlad90** [comment]
Hi @kimhung222 ,
Thanks for the bug report.

A version `0.4.1-dev.1` with a more informative error message has been uploaded to NPM. Next time you get an error message, post it here for better understanding of the problem and help in fixing it.

As for the partial lack of styles, I think the problem is in the `NextJS` cache. Try deleting the `.next` folder instead of editing the `next.config.js` file, or add an automatic deletion on startup, as it is done in the demo application [scripts](https://github.com/Dwlad90/nextjs-app-dir-stylex/blob/3c3f1132a4d08e7e010c4d34d7eed2babe86af29/package.json#L7-L8).

```json
 "predev": "rimraf .next",
 "prebuild": "rimraf .next",
```



Thanks for helping to improve the project!
