### ISSUE TITLE
Expected 'none' value of an ident token, css rule: *

### ISSUE THREAD

**Issue by HQ92** [Dwlad90/stylex-swc-plugin#84]
I'm getting an error of

`
Expected 'none' value of an ident token, css rule: * { color: oklch(from var(--xs74gcj) l c h / 0.5) }
frontend:dev: [2] Location: crates\stylex-shared\src\shared\utils\css\common.rs:497
`

The original stylex is:

```js
   import { grid, textColor, type GreaterThanIncSmallDesktop } from '@styles/global-tokens.stylex';

   const greaterThanIncSmallDesktop: GreaterThanIncSmallDesktop = `@media (min-width: 1024px)`;
   const s=stylex.create({   
    totalResults: {
      color: `oklch(from ${textColor.white} l c h / 0.5)`,
      // color: `#fff`,
      fontSize: {
        default: `calc(${grid.a} * 2.6)`,
        // eslint-disable-next-line @stylexjs/valid-styles
        [greaterThanIncSmallDesktop]: `calc(${grid.a} * 1.4)`,
      },
      lineHeight: '1em',
    },
   });
```

I'm not sure what is wrong here, i was using the babel compiler from the official stylexjs docs before, thought I'd try shifting to swc to see if it improved dev timings, but am coming up against this now. The project is a turborepo monorepo, with a separate ui package with stylexjs components, my next.config relating to this package is:

```js
const rootDir = path.join(__dirname, '../../');
const stylexPlugin = require('@stylexswc/nextjs-plugin')({
  rootDir,
  // Stylex RS compiler options
  dev: process.env.NODE_ENV !== 'production',
  genConditionalClasses: true,
  treeshakeCompensation: true,
  aliases: {
    '@styles/*': [path.join(__dirname, 'styles/*')],
    '@ui/*': [path.join(rootDir, 'packages/ui/*')],
  },
  unstable_moduleResolution: {
    type: 'commonJS',
    rootDir,
  },
});
```

I am using the latest versions of styleX as well as this swc plugin copied from the nextjs example in the repo:

```json
    "@stylexjs/babel-plugin": "^0.9.3",
    "@stylexjs/eslint-plugin": "^0.9.3",
    "@stylexjs/nextjs-plugin": "^0.9.3",
    "@stylexjs/open-props": "^0.9.3",
    "@stylexjs/stylex": "^0.9.3",
    "@stylexswc/nextjs-plugin": "0.4.1-dev.1",
    "@stylexswc/rs-compiler": "0.4.1-dev.1",
```

**Comment by Dwlad90** [comment]
Hi @HQ92,
Thanks for finding the bug and showing interest in this plugin.

The issue was fixed in #85 and wiil be available for use in version `0.4.1-rc.1` soon.

As for the build speed, I haven't checked the difference when using turborepo, but when building with `Webpack` the [demo](https://github.com/Dwlad90/nextjs-app-dir-stylex) builds almost 2 times faster than the original [StyleX demo](https://github.com/npm/nextjs-app-dir-stylex): 8-9 sec. with `SWC` vs 15-16 sec. with `babel`.

If you find any more bugs or have any suggestions, I'll be glad to help.
